# !/usr/bin/env python
# -*- coding:utf-8 -*-
# author : zerodel
# Readme:
#



__doc__ = '''

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''
__author__ = 'zerodel'


def fib():
    yield 1
    yield 2

    a, b = 1, 2
    while True:
        a, b = b, a + b
        yield b

sum = 0
for x in fib():
    if x%2 == 0:
        sum += x
    if x > 4*10**6:
        break
print(sum)

if __name__ == "__main__":
    pass